source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
target 'Bracelet' do
pod 'AFNetworking',  '~> 3.1.0'
pod 'MBProgressHUD'#HUD的提示
pod 'SDWebImage',  '~> 4.0.0’
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'pop'
pod 'ReactiveCocoa', '~>2.5'
pod 'UMengAnalytics-NO-IDFA'
pod 'RMessage'
pod 'YYKit'
#侧滑第三方
pod 'MMDrawerController', '~> 0.5.7'

# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'

# 集成微信(完整版14.4M)
pod 'UMengUShare/Social/WeChat'

# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMengUShare/Social/QQ'

# 集成新浪微博(完整版25.3M)
pod 'UMengUShare/Social/Sina'

#包含了下面几个第三方库被夹在进来了
#HexColors  转化颜色进制的第三方
#PPTopMostController
#自动找到当前控制器的最上面的控制器
#空数据的情况下的一些站位图和用户之间的交互
pod 'FORScrollViewEmptyAssistant'
#DZNEmptyDataSet  集成了这个

#跟踪手势在屏幕上的点击效果
pod 'FORGestureTrackDisplay'


end
